language: objective-c
osx_image: xcode9.2
xcode_sdk: iphonesimulator10.0

branches:
  only:
    - develop
    - master

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

# before_install:
#   - rvm install ruby
#   - gem install cocoapods
#   - gem install xcpretty -N
#   - brew update
#   - brew install swiftlint || true

script:
  - set -o pipefail
  # - travis_retry xcodebuild -workspace SwiftyJSON.xcworkspace -scheme "SwiftyJSON iOS" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
  # - travis_retry xcodebuild -workspace SwiftyJSON.xcworkspace -scheme "SwiftyJSON macOS" build-for-testing test | xcpretty
  # - xcodebuild -workspace CoinFindr.xcworkspace -scheme CoinFindr -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild clean test -project CoinFindr.xcodeproj -scheme CoinFindr -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
  - swiftlint

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725
